# Generated by Django 6.0.4 on 2026-05-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('schema_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('email', 'schema_name')},
            },
        ),
    ]
