# Generated by Django 6.0.4 on 2026-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskevidence',
            name='file_url',
        ),
        migrations.AddField(
            model_name='taskevidence',
            name='file_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
