# Generated by Django 6.0.4 on 2026-05-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
