# Generated by Django 6.0.4 on 2026-05-22 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('BASE', 'Base'), ('PLUS', 'Plus'), ('PRO', 'Pro')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('BASE', 'Base'), ('PLUS', 'Plus'), ('PRO', 'Pro')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.tenant')),
            ],
        ),
    ]
